version: '3'

services:
  traefik:
    image: traefik
    container_name: trafik
    networks:
        - web
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml 
      - ./certs/:/certs/
      - ./acme.json:/acme.json 
    labels:
      - "traefik.port=8080"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:masterserver.cf; PathPrefixStrip: /traefik"

networks:
  web:
    external:
      name: web

  
