version: '3'

services:
  traefik:
    image: traefik
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/data/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=samuellucas0603@gmail.com"
      - "--docker"
      - "--docker.domain=eventeasy.cf"
      - "--docker.watch"
    networks:
        - web
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.port=8080"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:eventeasy.cf; PathPrefixStrip: /traefik"

networks:
  web:
    external:
      name: web
  default:
    driver: overlay